package view;

import aplication.Atendimento;
import aplication.DAO;
import javax.swing.JOptionPane;
import aplication.Especialidade;

/**
 *
 * @author 823143267
 */
public class TelaRegistrarTriagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistrarTriagem
     */
    public TelaRegistrarTriagem() {
        initComponents();
        
        tipoAten();
        especialidade();
        status();
    }
    
    public void tipoAten(){
        buttonGroup1.add(chUrgencia);
        buttonGroup1.add(chPreferencial);
        buttonGroup1.add(chEmergencia);
        buttonGroup1.add(chPadrao);
        
    }
    
    public void especialidade(){
        buttonGroup2.add(cBOrtopedia);
        buttonGroup2.add(cBCardiologia);
    }
    
    public void status(){
        buttonGroup3.add(cBToken);
        buttonGroup3.add(cBTriagem);
        buttonGroup3.add(cBAtendimento);
        buttonGroup3.add(cBConsulta);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSintomas = new javax.swing.JTextField();
        txtPressaoArt = new javax.swing.JTextField();
        txtFrequenciaCard = new javax.swing.JTextField();
        btnVoltarRegistro = new javax.swing.JButton();
        btnRegistrarTriagem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCpfPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chUrgencia = new javax.swing.JCheckBox();
        chPreferencial = new javax.swing.JCheckBox();
        chEmergencia = new javax.swing.JCheckBox();
        chPadrao = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtIdAtendimento = new javax.swing.JTextField();
        cBOrtopedia = new javax.swing.JCheckBox();
        cBCardiologia = new javax.swing.JCheckBox();
        cBToken = new javax.swing.JCheckBox();
        cBTriagem = new javax.swing.JCheckBox();
        cBAtendimento = new javax.swing.JCheckBox();
        cBConsulta = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Frequência Cardíaca");

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Temperatura");

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Sintomas");

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Pressão Arterial");

        txtSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSintomasActionPerformed(evt);
            }
        });

        txtPressaoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPressaoArtActionPerformed(evt);
            }
        });

        txtFrequenciaCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrequenciaCardActionPerformed(evt);
            }
        });

        btnVoltarRegistro.setBackground(new java.awt.Color(102, 153, 255));
        btnVoltarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarRegistro.setText("Voltar");
        btnVoltarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarRegistroActionPerformed(evt);
            }
        });

        btnRegistrarTriagem.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarTriagem.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTriagem.setText("Registrar");
        btnRegistrarTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTriagemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Tipo de Atendimento");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Status do Atendimento");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Especialidade");

        txtCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPacienteActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("CPF do Paciente");

        chUrgencia.setBackground(new java.awt.Color(51, 102, 255));
        chUrgencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chUrgencia.setForeground(new java.awt.Color(255, 255, 255));
        chUrgencia.setText("Urgência");
        chUrgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chUrgenciaActionPerformed(evt);
            }
        });

        chPreferencial.setBackground(new java.awt.Color(51, 102, 255));
        chPreferencial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chPreferencial.setForeground(new java.awt.Color(255, 255, 255));
        chPreferencial.setText("Preferencial");

        chEmergencia.setBackground(new java.awt.Color(51, 102, 255));
        chEmergencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        chEmergencia.setText("Emergência");

        chPadrao.setBackground(new java.awt.Color(51, 102, 255));
        chPadrao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chPadrao.setForeground(new java.awt.Color(255, 255, 255));
        chPadrao.setText("Padrão");

        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Id Atendimento");

        txtIdAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAtendimentoActionPerformed(evt);
            }
        });

        cBOrtopedia.setBackground(new java.awt.Color(51, 102, 255));
        cBOrtopedia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBOrtopedia.setForeground(new java.awt.Color(255, 255, 255));
        cBOrtopedia.setText("Ortopedia");

        cBCardiologia.setBackground(new java.awt.Color(51, 102, 255));
        cBCardiologia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBCardiologia.setForeground(new java.awt.Color(255, 255, 255));
        cBCardiologia.setText("Cardiologia");

        cBToken.setBackground(new java.awt.Color(51, 102, 255));
        cBToken.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBToken.setForeground(new java.awt.Color(255, 255, 255));
        cBToken.setText("Token");

        cBTriagem.setBackground(new java.awt.Color(51, 102, 255));
        cBTriagem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBTriagem.setForeground(new java.awt.Color(255, 255, 255));
        cBTriagem.setText("Triagem");
        cBTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBTriagemActionPerformed(evt);
            }
        });

        cBAtendimento.setBackground(new java.awt.Color(51, 102, 255));
        cBAtendimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        cBAtendimento.setText("Atendimento");
        cBAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAtendimentoActionPerformed(evt);
            }
        });

        cBConsulta.setBackground(new java.awt.Color(51, 102, 255));
        cBConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cBConsulta.setForeground(new java.awt.Color(255, 255, 255));
        cBConsulta.setText("Consulta Médica");

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resgistrar Triagem");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPressaoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrequenciaCard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtIdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtSintomas))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cBTriagem)
                                .addComponent(jLabel8)
                                .addComponent(cBAtendimento)
                                .addComponent(cBConsulta)
                                .addComponent(cBToken)
                                .addComponent(cBOrtopedia)
                                .addComponent(cBCardiologia)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(chUrgencia)
                            .addComponent(chPreferencial)
                            .addComponent(chEmergencia)
                            .addComponent(chPadrao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(chUrgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chPreferencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chEmergencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chPadrao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBToken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cBTriagem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBAtendimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBConsulta)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBOrtopedia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBCardiologia))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFrequenciaCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPressaoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFrequenciaCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrequenciaCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrequenciaCardActionPerformed

    private void txtPressaoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPressaoArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPressaoArtActionPerformed

    private void btnRegistrarTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTriagemActionPerformed
        int idAtendimento = Integer.parseInt(txtIdAtendimento.getText());
        int Especialidade_idEspecialidade = 2;
        String paciente_cpf = txtCpfPaciente.getText();
        //int tipo = Integer.parseInt(txtTipoAten.getText());
        int tipo = 0;

        if(chUrgencia.isSelected()){
            tipo = 1;
        } else if(chPreferencial.isSelected()){
            tipo = 2;
        } else if(chEmergencia.isSelected()){
            tipo = 3;
        } else if(chPadrao.isSelected()){
            tipo = 4;
        }
         
        float pressao_art = Float.parseFloat(txtPressaoArt.getText());
        float temperatura = Float.parseFloat(txtTemperatura.getText());
        String sintomas = txtSintomas.getText();
        float frequencia_card = Float.parseFloat(txtFrequenciaCard.getText());
        int status_aten = 0;
        
        if(cBToken.isSelected()){
            status_aten = 1;
        } else if(cBTriagem.isSelected()){
            status_aten = 2;
        } else if(cBAtendimento.isSelected()){
            status_aten = 3;
        } else if(cBConsulta.isSelected()){
            status_aten = 4;
        }
        
        
        int nome = 0;
        
        if(cBOrtopedia.isSelected()){
            nome = 1;
        } else if (cBCardiologia.isSelected()){
            nome = 2;
        }
        
        int idEspecialidade = 2;
        
        
        try{
            Atendimento atendimento = new Atendimento(idAtendimento, Especialidade_idEspecialidade, paciente_cpf, tipo, pressao_art, temperatura, sintomas, frequencia_card, status_aten);
            Especialidade especialidade = new Especialidade(idEspecialidade, nome);
            
            DAO dao = new DAO();
            dao.registrar(atendimento);
            dao.especialidade(especialidade);
            JOptionPane.showMessageDialog(null, "Inserção concluída");
            //LoginTela lt = new LoginTela();
            //lt.setVisible(true); //pra ficar visivel
            txtPressaoArt.setText("");
            txtTemperatura.setText("");
            txtSintomas.setText("");
            txtFrequenciaCard.setText("");
            //this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Inserção não concluída");
        }
    }//GEN-LAST:event_btnRegistrarTriagemActionPerformed

    private void btnVoltarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarRegistroActionPerformed
        TelaRedirecionamento tr = new TelaRedirecionamento();
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarRegistroActionPerformed

    private void chUrgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chUrgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chUrgenciaActionPerformed

    private void txtIdAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAtendimentoActionPerformed

    private void cBTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBTriagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBTriagemActionPerformed

    private void cBAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBAtendimentoActionPerformed

    private void txtSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSintomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSintomasActionPerformed

    private void txtCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrarTriagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTriagem;
    private javax.swing.JButton btnVoltarRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cBAtendimento;
    private javax.swing.JCheckBox cBCardiologia;
    private javax.swing.JCheckBox cBConsulta;
    private javax.swing.JCheckBox cBOrtopedia;
    private javax.swing.JCheckBox cBToken;
    private javax.swing.JCheckBox cBTriagem;
    private javax.swing.JCheckBox chEmergencia;
    private javax.swing.JCheckBox chPadrao;
    private javax.swing.JCheckBox chPreferencial;
    private javax.swing.JCheckBox chUrgencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtFrequenciaCard;
    private javax.swing.JTextField txtIdAtendimento;
    private javax.swing.JTextField txtPressaoArt;
    private javax.swing.JTextField txtSintomas;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
